// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const provider = process.env.DATABASE_PROVIDER?.toLowerCase() ??
  ((process.env.DATABASE_URL ?? "").startsWith("postgres") ? "postgresql" : "sqlite");
const schema = provider === "postgresql" ? "prisma/schema.postgres.prisma" : "prisma/schema.prisma";

export default defineConfig({
  schema,
  migrations: {
    path: "prisma/migrations",
    seed: "node --import tsx prisma/seed.dev.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
